### PR TITLE
GitHub Pages Deploy

### PR DESCRIPTION
**Pull request by Ajedi32**
An attempt to get metalsmith.io deployed on GitHub pages.

### CODE REVIEW

**Comment by Ajedi32** [comment]
The deploy isn't automated right now, but after the changes above all you need to do to deploy to GitHub Pages is run `make build` and then push the contents of the `/build` directory to the master branch of `https://github.com/metalsmith/metalsmith.github.io`.

**Comment by ismay** [comment]
To simplify things you could also use the [gh-pages](https://www.npmjs.com/package/gh-pages) module, like so: https://github.com/ismay/ismay.github.io/blob/development/deploy.js. It takes care of moving build results to a certain branch and then pushes them to the correct repo.

**Comment by Ajedi32** [comment]
Yeah, I'm currently planning to use [grunt-gh-pages](https://github.com/tschaub/grunt-gh-pages), which is very similar.

**Comment by ismay** [comment]
> Yeah, I'm currently planning to use grunt-gh-pages, which is very similar.

Ah ok. Yeah I saw the grunt build process in #193, using a grunt plugin would make sense in that case.

If after #193 metalsmith.io moves to gh-pages (which I'd recommend over heroku), using gh-pages directly would simplify things even further (less intermediary processes). But we can see after #193. In any case I'd be happy to help with the transition to gh-pages.

**Pull request merged**
