### PR TITLE
Add plugin JSON insteadof Markdown

### PR DESCRIPTION
**Pull request by boeckMt**
This Plugin is to use JSON files in addition to markdown files to write your content.

### CODE REVIEW

**Comment by webketje** [comment]
All plugins listed here are available via NPM. As the homepage mentions:
> Metalsmith and its plugins can be installed with npm

Could you publish this plugin on NPM and/or create a Git tag and Github release, and mention in the readme that the plugin can be installed with `npm i -D git://github.com/boeckMt/metalsmith-json-insteadof-md.git` ?

**Comment by boeckMt** [comment]
Hey @webketje thanks for the hint, I will publish it on npm and also update the readme to better show how to use it.

**Comment by boeckMt** [comment]
Now I have published it on npm you can find it here https://www.npmjs.com/package/@boeckmt/metalsmith-json-insteadof-md.
Thanks for the advise.

**Comment by webketje** [comment]
> Now I have published it on npm you can find it here https://www.npmjs.com/package/@boeckmt/metalsmith-json-insteadof-md.
> Thanks for the advise.

Tyvm, no further objections :)

**Comment by boeckMt** [comment]
Hey @webketje I saw that I forgot to add the `plugin.npm` attribute and because of the npm **scope** I used the shields for npm are not working correctly see https://metalsmith.io/#the-community-plugins and filter for 'json insteadof'.

I have created a new branch on my fork https://github.com/metalsmith/metalsmith.io/compare/master...boeckMt:add-plugin-with-scope.
Should i create a new pull request or is it to much effort for you?

**Comment by webketje** [comment]
Hi @boeckMt,
Yes you have the @org special use case.
Reviewed your changes, looks correct to me, please send in the PR

**Pull request merged**
