### PR TITLE
add auto deploy when new changes merged to master

### PR DESCRIPTION
**Pull request by lambtron**
https://github.com/metalsmith/metalsmith.io/issues/149

### CODE REVIEW

**Comment by lambtron** [comment]
@Ajedi32 Can you take a look at this? Not sure if I did this correctly (my first time with Travis!)

Thanks!

**Comment by lambtron** [comment]
Looks like there is a build error about not having a Rakefile?

https://travis-ci.org/metalsmith/metalsmith.io

Should Travis be enabled on every push?

**Comment by Ajedi32** [comment]
Looks like Travis thinks this is a Ruby-based project for some reason. You'll probably want to take a look at this guide for setting Travis up for Node.js projects:

https://docs.travis-ci.com/user/languages/javascript-with-nodejs

**Comment by Ajedi32** [comment]
The deploy part is a step that only happens after the "tests" or in this case the build, succeeds. So first we need to get Travis to build the project, then once that's working it should be able to deploy.

**Comment by Ajedi32** [comment]
Looking better. I'll bet if we merged this now it would trigger the auto-deploy. There's still a few remaining issues to solve first though.

First, it looks like Travis is currently planning to deploy once for every different version of Node we're testing with. You can fix that by using [conditional releases](https://docs.travis-ci.com/user/deployment/#Examples-of-Conditional-Releases-using-on%3A) (probably `on: node: '4.2'` or something along those lines), or by only testing with a single Node version.

The second issue is that it doesn't look like Travis is building the project, it's just running `npm test`, which currently does nothing. You'll probably want to add a pretest [script](https://docs.npmjs.com/misc/scripts) to `package.json` that runs `make components` before deploying, assuming Heroku doesn't do that already when you push to it. (Does it?)

Finally, it might be worth adding some tests to the project to be sure Travis doesn't deploy a broken revision to production. Even though it will only deploy stuff pushed to master, it's always a good idea to make the deploy process as idiot-proof as possible. Maybe that can go in a separate PR though...

**Comment by lambtron** [comment]
Thanks for your feedback! This is helpful.

I think heroku automatically builds upon deploy.

Do you think my changes addressed your issues?

**Comment by Ajedi32** [comment]
Looks good as far as I can tell. I guess the only way to be sure though is to merge it and see what happens.

Go ahead and merge. I'd do it myself, but there's a small chance that merging this will break [metalsmith.io](http://metalsmith.io/) (if something goes seriously wrong with the deploy), so it'd be best if someone with direct push access to Heroku is standing by just in case.

**Comment by lambtron** [comment]
:+1:

**Comment by Ajedi32** [comment]
You gonna hit the button then? :wink:

**Comment by Ajedi32** [comment]
So far so good. Looks like it's deploying now: https://travis-ci.org/metalsmith/metalsmith.io/jobs/102878628

**Comment by Ajedi32** [comment]
```
-----> Launching...
       Released v93
       https://metalsmith.herokuapp.com/ deployed to Heroku
heroku build still pending
Already up-to-date!
# HEAD detached at 5f61267
nothing to commit, working directory clean
Dropped refs/stash@{0} (a75d6b525e39b59ebb1ce1d01862bddce37bd6d9)
Done. Your build exited with 0.
```

:tada:

**Comment by lambtron** [comment]
Sweet!! Thanks for helping me through that :)

**Comment by Ajedi32** [comment]
No problem. :smile:

**Comment by Ajedi32** [comment]
Hmm, hold on... 

It *looks* like the deploy succeeded based on the log, but I'm not seeing the changes showing up on metalsmith.io. Maybe that `heroku build still pending` message has something to do with it?

Can you check what revision Heroku thinks is currently deployed?

**Comment by Ajedi32** [comment]
Looks like you should be able to see it here: https://dashboard.heroku.com/apps/metalsmith/activity

**Comment by Ajedi32** [comment]
Heh... now that I actually look at it, Heroku seems to have a built-in way to auto-deploy changes from GitHub: https://dashboard.heroku.com/apps/metalsmith/deploy/github :open_mouth:

Though I guess the advantage of using Travis is that you can set it to only deploy when the tests pass.

**Comment by Ajedi32** [comment]
Actually... it seems that's not an advantage either: https://devcenter.heroku.com/articles/github-integration#automatic-deploys :stuck_out_tongue_winking_eye:

**Comment by der-On** [comment]
@Ajedi32 that looks exactly like what you want, why not use it?

**Pull request merged**
