### PR TITLE
Added build verification and eslint for consistency.

### PR DESCRIPTION
**Pull request by woodyrew**
Verification is relatively rudimentary at the moment but more specific tests can be added as required.

ESLint added for code consistency.

### CODE REVIEW

**Comment by woodyrew** [comment]
@lambtron or @Ajedi32 Any idea what version of node is running on the Heroku server?

eslint doesn't support node < v4.

**Comment by woodyrew** [comment]
I think it's on `v0.12` according to the deploy section in `.travis.yml`

**Comment by woodyrew** [comment]
Fixes #195

**Comment by Ajedi32** [comment]
Actually, according to Heroku it's likely using the latest LTS (or something similar to that): https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

You can set whatever version you want with the "engines" key in package.json: https://docs.npmjs.com/files/package.json#engines

**Comment by woodyrew** [comment]
Ah cool. I'll have a play, I think it'd be good to on node _stable_ (`v6` at the moment).

I was going by: https://github.com/metalsmith/metalsmith.io/blob/master/.travis.yml#L11

**Comment by Ajedi32** [comment]
The `.travis.yml` file indicates what Travis is building the project with, not what Heroku builds it with. My current understanding is that it works like this:

1. Travis builds the project and runs tests
2. If the tests pass, and the currently running Travis build is using Node v0.12, the current commit is pushed to Heroku via git (no built files, only the existing commit)
3. Heroku builds the project (using it's own rules which are unrelated to Travis).
4. If the build succeeds, Heroku runs the newly built project in production

**Comment by woodyrew** [comment]
You could be correct but Travis can trigger Heroku deployment and we certainly have that in the [`.travis.yml`](https://github.com/metalsmith/metalsmith.io/blob/master/.travis.yml#L11)

See: [Heroku Deployment - Travis CI](https://docs.travis-ci.com/user/deployment/heroku#Conditional-Deploys)

I'll do some testing and let you know.

**Comment by woodyrew** [comment]
Metalsmith.io is running on Node `v6.6.0` now.

The node version in `.travis` _deploy_ section is set to `node: 6.6` this is to match the Heroku version of node being used.
_engine_ in `package.json` is also set to `6.6` - this is what the node version on Heroku is.

**Pull request merged**
