### PR TITLE
Add Image Aspect Ratio and Native Lazy Loading

### PR DESCRIPTION
**Pull request by tonygustafsson**
Add two of my first plugins. Used in production already.

### CODE REVIEW

**Comment by webketje** [comment]
Hi @tonygustafsson, thank you for your contribution!

As part of the admission process to the plugin listing, I do a quick plugin review. Unfortunately both these plugins did not meet some checks. I'll list them here so you can address them:

**metalsmith-native-lazy-loading**
- The readme says `pattern: ['**/*.png', '**/*.jpg', '**/*.webp']` but the default is `*/**.html`. No checks are done on the `src` property of the image tags. It seems like you mixed documentPattern & imagePattern. You could use `pattern` to target filepaths (as do most other plugins) and `extensions` to target specific img tags.
- Currently even `` will be replaced with `lazy`. Although still invalid, you can fix this easily by moving the `$1` sign to before the extra loading tag (see SO why: https://stackoverflow.com/questions/26341507/can-an-html-element-have-the-same-attribute-twice), or with some extra work check whether the property exists and not replace its value.

*Optional*

- At https://github.com/tonygustafsson/metalsmith-native-lazy-loading/blob/main/index.js#L30 you can re-use imagesFound.

**metalsmith-image-aspect-ratio**
- Currently even images with already written style/src/width attributes are replaced with custom attributes. This is not desirable for many use cases, e.g. if the plugin is executed after `metalsmith-layouts` and header images belonging to template files attributes' are replaced. One partial solution is to include a section in the docs about plugin order, though will not solve all issues. Better would be to parse all these attributes as regex groups and add to their contents instead of replacing them.

**both**
- Plugins only work on locally referenced images (e.g. many static site owners will want to upload their images to an external service like Imgur). A better approach would be to scan the `src` tags and request the images through HTTP, then get their size.
If this is (understandably) too much to ask, could you add a notice in the README that the plugins only operate on locally referenced images.

**Comment by tonygustafsson** [comment]
Really great to see that you are this serious about your plugins :) I will take a look at these suggestions and come back to you.

**Comment by tonygustafsson** [comment]
@webketje Hello! I'm back.

**metalsmith-native-lazy-loading**

- Fixed readme confusion
- Started using cheerio instead, realized it was almost impossible to avoid creating bugs in some cases. With cheerio I could just fetch all images without loading attribute and set it. Not excellent for performance of course, but worth it. Could also fetch only images in articles - not the template where it's not giving alot of value.
- Optmized some code
- Fixed depenendcy problem

Your comment regarding only local images is not relevant here. It is for metalsmith-image-aspect-ratio though. Don't have time to write unit tests at the moment.

**metalsmith-image-aspect-ratio**

- Using cheerio here as well, only for article images and will not overwrite style attribute but append to it.
- Info in readme egarding only static images.
- Fix debug info confusion
- Fixed the parameters... don't know if I understood you correctly. But I'm using just pattern now to match html. And another one for imageExtensions.

It's kind of hard to figure out how to write good plugins. I just got your skeleton and lots and lots of plugins to study. But I don't know which ones are good and which ones were good three years ago :) Send me useful links if you want to.

**Comment by webketje** [comment]
@tonygustafsson Perfect, I wanted to suggest cheerio but forgot. Did a quick scan again, native lazy loading all good.

metalsmith has been in an ownership transition phase since 2020, and we have plans to revitalize / re-organize the existing hard-to-navigate ecosystem; a better guide on how to write plugins is one of the to-do's. For now, the best examples are under https://github.com/metalsmith

I will merge your PR, however I leave you with this test run debug feedback for image-aspect-ratio: 

```
  metalsmith:imageAspectRatio imageAspectRatio couldn't find dimensions for https://via.placeholder.com/300x400 +12ms
  metalsmith:imageAspectRatio imageAspectRatio couldn't find dimensions for https://via.placeholder.com/300x400 +7ms
  metalsmith:imageAspectRatio imageAspectRatio couldn't find dimensions for https://via.placeholder.com/300x400 +17ms
  metalsmith:imageAspectRatio imageAspectRatio couldn't find dimensions for https://via.placeholder.com/300x400.png +9ms
  metalsmith:imageAspectRatio imageAspectRatio couldn't find dimensions for https://via.placeholder.com/300x400.png +8ms
  metalsmith:imageAspectRatio imageAspectRatio is done. Successfully put aspect ratio on 5 images. +8ms
```
The issues are:

- Reports that aspect-ratio was put on all images, but succeeded for 0.
- Required to use within specific class `.article__content` (can be omitted from selector, users can target files they want to use the plugin for by using `pattern` and `imageExtensions` and plugin order in metalsmith build chain)
- Not sure why you're doing the `.replace('../', '')`, looks like smth. specific to your setup (storing images outside of metalsmith src dir or moving the html file)

**Comment by tonygustafsson** [comment]
@webketje OK I hear you regarding the docs. I'll try to check out more plugins before I create new ones :)

- I've fixed the counter so it won't count ignored/failed images
- Yes, the ../ was my special case, yes. It has been fixed. I figured it didn't bother anyone and if anyone were as stupid as I was, it would still work ;) The problem I had was that the files reported by metalsmith was not exactly the same as referenced in the HTML/Markdown. I've changed the approach now:
    -  Since all images and their width/height are stored in an object, it will never include external images. Which is fine. When it tries to find the image dimensions it will not succeed. It will only warn through debug() if it's a local file now though.
    - Internal images can be referenced as img/image.jpg, ./img/image.jpg, ../img/image.jpg or pretty much any combination of dots and dashes. So in order to match them with the image paths from metalsmith I just remove leading dots and dashes. Seems to work for my environment.
 - The last thing regarding ```.article__content``` I don't fully agree. It parses HTML so the order of the plugin shouldn't matter. The pattern only points to HTML documents and extensions doesn't know anything about paths. I think it's good to target only article images and not potential layout images. These are easy to add aspect ratio to manually if you wanted to.

**Comment by webketje** [comment]
@tonygustafsson regarding your last point, I don't think you understand what I mean.
As a metalsmith user I expect to do `npm i metalsmith-image-aspect-ratio` and then `.use(imageAspectRatio({ }))` to work on all files and images. I can narrow the selection by passing `.use(imageAspectRatio({ pattern: 'articles/**/*', imageExtensions: ['png'] }))`. What I absolutely don't want is being forced to use the exact className `.article__content` because I hate BEM (playing devil's advocate here) and I want to target it at `.article.body`.

**Comment by tonygustafsson** [comment]
@webketje Thank you for teaching me and it feels great to be a part of this :) I've taken care of making the image container class name optional.

**Pull request merged**
