### PR TITLE
submit metalsmith-models plugin

### PR DESCRIPTION
**Pull request by jaichandra**
Removed 'Metalsmith' part from the name.

### CODE REVIEW

**Comment by Ajedi32** [comment]
You might want to remove the "Metalsmith" part from the `name` field (and reorder it accordingly). Almost all of the plugins in this list have names that start with "Metalsmith", so it that part of the name is omitted to remove redundancy.

**Comment by jaichandra** [comment]
@Ajedi32 When do you plan to publish the latest plugins.json to the website?

**Comment by Ajedi32** [comment]
Yeah, sorry. We tried setting up an automated deploy system awhile back #149 but it's not quite working yet. I don't have push access to the site itself so you'll have to talk to @lambtron or one of the other Segment employees. I'll ping someone in the chat to take a look at it...

**Comment by lambtron** [comment]
Sorry about that! I went and rebuilt the site. New plugins should be live!!

**Comment by jaichandra** [comment]
Thanks

**Comment by jaichandra** [comment]
Hi @lambtron, the plugin has gone missing again from the website. Can you please check.
Thanks!

**Pull request merged**
