### PR TITLE
Adding walkthrough for #238. Updating src/index.md to add links to th…

### PR DESCRIPTION
**Pull request by lukehler**
Adding walkthrough for #238.

### CODE REVIEW

**Comment by axe312ger** [comment]
I like the content but that would just bloat the single page layout even more.

We should get this whole page splited up into multiple pages before we make it even longer.

**Comment by lukehler** [comment]
Thanks for the bump, @axe312ger

I'd suggest taking a second look at the code (does `metalsmith-layouts` still work in this example?) and the only other thing to note is that __the walkthrough is already on a second page__. I didn't add any real navigation, just sprinkled a few inline links on the existing index.

**Comment by axe312ger** [comment]
Ahh great, so if this is already on a second page this is ✅ 

The concerns with the `metalsmith-layout` changes are serious, please have a look if it still works like this.

Otherwise we should speed up here and get it out there :)

**Comment by lukehler** [comment]
Updated and tested for changes to metalsmith-layouts.

Also tidied up the formatting of file names versus commands while I was in there. Should now be consistently formatted as _dir-name/_, _file-name.ext_, and `command or code`.

**Comment by axe312ger** [comment]
Looks fine to my from technical side. Did not check the content itself in detail

Pushing to @woodyrew, what do you think? I guess it won't hurt if we merge it in for the website <3

**Comment by woodyrew** [comment]
Thanks for the PR. Please resolve the conflicts.

**Comment by webketje** [comment]
@woodyrew  please see #301

**Pull request merged**
