### PR TITLE
added webpack 2 plugin

### PR DESCRIPTION
**Pull request by leviwheatcroft**
This PR just adds metalsmith-webpack-2.

I considered removing metalsmith-webpack because [it's dead](https://github.com/christophercliff/metalsmith-webpack/issues/25), but it felt like poor form to remove someone else's plugin (even though I'm a maintainer). Any thoughts?

### CODE REVIEW

**Comment by Ajedi32** [comment]
Not sure how to handle removing plugins. Personally I see the plugin list on metalsmith.io as more of a package repository than a curated list, so from that perspective it makes sense to just leave old plugins there indefinitely.

**Comment by leviwheatcroft** [comment]
@Ajedi32 agreed, removing packages might be a dark path to go down :)

**Comment by Ajedi32** [comment]
I noticed you added a lockfile. No idea if that was on purpose or not, but I think it's probably a good idea to have one of those anyway.

**Comment by leviwheatcroft** [comment]
no not on purpose, should've checked what I was committing, current version of npm generates them automatically.

**Pull request merged**
